name: Deploy to ECR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        role-session-name: ecrsession
        aws-region: us-east-2

    - name: Login to ECR using aws-actions
      id: login-ecr
      with:
        mask-password: true
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Login to ECR using docker
      uses: docker/login-action@v3
      env: 
        TEST_ENV_VAR: pasta
        DOCKER_USER: docker_username_${{ secrets.AWS_ACCOUNT }}_dkr_ecr_${{ secrets.AWS_REGION_UNDERSCORE }}_amazonaws_com
        DOCKER_PW: docker_password_${{ secrets.AWS_ACCOUNT }}_dkr_ecr_${{ secrets.AWS_REGION_UNDERSCORE }}_amazonaws_com
      with:
        registry: ${{ steps.login-ecr.outputs.registry }}
        username: ${{ steps.login-ecr.outputs['${DOCKER_USER}'] }}
        password: ${{ steps.login-ecr.outputs['${DOCKER_PW}'] }}
     
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: build and push
      uses: docker/build-push-action@v5
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mwaa-spike-private
        IMAGE_TAG: ${{ steps.login-ecr.outputs.registry }}/mwaa-spike-private:temp-test
      with:
        context: .
        platforms: linux/x86_64
        push: true
        secrets: |
          "secret_stuffs=${{ secrets.VERY_SECRET_VALUE }}"
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/mwaa-spike-private:temp-test
    